### ISSUE TITLE
Growth rate text still shows despite off in parameters

### ISSUE THREAD

**Issue by Limyx826** [F1rrel/RenewedVillageGrowth#103]
![image](https://user-images.githubusercontent.com/38696851/182414110-5483c5dc-9307-4a7b-8373-73dac67cea4e.png)

**Comment by F1rrel** [comment]
This is intentional behavior. Growth text, randomization type, show cargo types from start and minimal population thresholds are only changeable before the game script starts. They are changeable (not grayed out) so that they can be modified in the scenario editor. It should be possible to make the growth text changeable, will consider it.
