### ISSUE TITLE
Feature Request: support AXIS

### ISSUE THREAD

**Issue by TransshipmentEnvoy** [F1rrel/RenewedVillageGrowth#109]
[AXIS](https://github.com/EmperorJake/AXIS.git) is the successor to XIS.

**Comment by F1rrel** [comment]
Thanks for the info, will add it with a new release.

**Comment by F1rrel** [comment]
There was an issue with procedural generation which caused cargo categories to be changed after loading of the game. https://github.com/F1rrel/RenewedVillageGrowth/pull/110

Checking the result of procedural generation, the cargo categories look fine (See image below from AXIS 2.0.1 Alpha). Also because it is still in alpha, the cargos can still change which would require new major release to fix it. So for now I will keep it at procedural generation and if there will be a problem with it, it can be fixed easier.

![image](https://user-images.githubusercontent.com/22470227/218270867-1ad1eaee-5d62-4c59-875c-b803994858f3.png)
