### ISSUE TITLE
Script doesn't seem to work in 14.0 or JGR 0.58.3

### ISSUE THREAD

**Issue by DmytroBashynskiy** [F1rrel/RenewedVillageGrowth#141]
Hello!

I've been playing with your script in 13.4 and it was a blast. After I had upgraded to 14.0 recently and later to JGR 0.58.3 I noticed the script does not work correctly, if at all.

The settings haven't been changed from the default.

It seems to assign the cargo categories correctly, in "Local Authority" I can clearly see the requirements as they pop up, but houses never start to accept the required cargo. I've tested this with Improved Town Industries 2 set, FIRS3 and PIRS 2022. Both with default houses, or with NewGRF houses (Swedish Houses Early Mod, Total Town Replacement Set). 

Also, the growth itself works weirdly. In some towns I had a good passenger service and mail ONLY and the town grew into 5000 inhabitants without supplying ANY of higher tier cargo. In other towns the population behaved as intended, it stopped on 1000 inhabitants. Then I provided them with Food, which was a 2nd category cargo with ITI2, and the growth resumed, slowing down at around 3.5k inhabitants.

I had made the loading list to have only the industry set with or without the houses. Stations dont show the required NewGrf cargoes as accepted and don't consume them if delivered. I have conducted these tests on both 14.0 and JGR 0.58.3.

**Comment by F1rrel** [comment]
Hi,

A game script cannot change what town buildings accept as cargos, only NewGRF can do that. In order to provide required cargo type to a town, that town needs to have an industry that accepts that cargo type. To best way to know that providing the cargo type to a industry will fullfill the town needs, the industry will be named based on the town (renaming the industry to another town name will not work). If there is no industry that accepts that type of cargo, it is required to fund that industry near that town, which adds another use of the abundant money that can be earned in this game.

There are two systems changing town growth:
1. Limiter: when not enough passangers and mails are transported out of town (Passangers last month 300 max 600 means 50% transported), it will say "Not enough transported out of town: <cargo types that should be improved>". This rule requires having the town covered with passanger and mail service. When the town grows out of the catchment area of these stations, the growth will completely stop.
2. Reducer: Fullfulling cargo categories increases the speed of town growth, but cannot stop the growth, only slow it down drastically. The better fulfilled percentage and the higher the town population, the quicker the town will grow.

I have tested it on 14.0 and it seems to work as expected.

![image](https://github.com/F1rrel/RenewedVillageGrowth/assets/22470227/059c51ce-790b-49f4-b650-7e446f28901a)
