### ISSUE TITLE
Industry stabilizer with XIS on dedicated server

### ISSUE THREAD

**Issue by F1rrel** [F1rrel/RenewedVillageGrowth#90]
Scitor

hmm, I've got something strange going on with RenewedVillageGrowth and XIS. When using the IndustryStabilizer option to spawn new industries on map start, it only works in SP, but not on dedicated. the script just hangs at "Funding industry Coal Mine", no further logs, no new industries appear, no town growth takes place. In SP, same setting creates like 500 industries and unpauses game afterwards.. this is in combination with XIS, with disabled "prevent industries opening", and manual funding works as well as prospecting. tested with RVG v8.0

**Comment by scitor** [comment]
I've looked a bit into the code, specifically the `if`-statement [here](https://github.com/F1rrel/RenewedVillageGrowth/blob/b92c15c99ebc2616e4c10f67f766a83de8a8c50a/industry.nut#L350).
When replaced with
```
local res_can = GSIndustryType.CanProspectIndustry(industry_type);
Log.Info("can " + (res_can?1:0) + " " + industry_type, Log.LVL_DEBUG);

local res_pros = GSIndustryType.ProspectIndustry(industry_type);
Log.Info("pros " + (res_pros?1:0) + " " + industry_type, Log.LVL_DEBUG);
        
if (res_can && res_pros) { ...
```
the console prints `can 1 1` but hangs afterwards, which wouldn't be a script problem?

**Comment by scitor** [comment]
Apparently the "pause" on a server is different than "pause" on singleplayer.
It turns out, in server mode the game needs 
`construction.command_pause_level` at 3 (_When paused allow: All actions_)
to prospect industries... funny because it paused itself.

I always have this at 1 (_All non-constructive_) but in SP the script even works with 0 (just tested).

A quick test confirms, moving `ProspectRawIndustry` out of `Init` (behind the `Unpause`) starts prospecting (while the game runs).

**Comment by F1rrel** [comment]
Thanks for finding the cause of this issue. I would fix it by temporarily enabling building while paused, I still want to prospect them during the pause so you start the game fully initialized.
